# Generated by Django 4.0.3 on 2022-03-26 23:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 3, 26, 23, 53, 12, 64404, tzinfo=utc))),
            ],
        ),
    ]
